#@FruitShelfApi_HostAddress = http://localhost:5138
@FruitShelfApi_HostAddress = http://localhost:5000

GET {{FruitShelfApi_HostAddress}}/api/products/
X-Correlation-ID: 02e55958-51e8-4505-b3ff-6d065f3a6699
Accept: application/json

###

GET {{FruitShelfApi_HostAddress}}/api/products/1
X-Correlation-ID: 2cd28868-04a7-42ec-aa9f-68ab0baf28bc
Accept: application/json

###

GET {{FruitShelfApi_HostAddress}}/api/products/10
X-Correlation-ID: e7319a6e-899d-413d-9ddb-d1848717bb98
Accept: application/json

###
GET {{FruitShelfApi_HostAddress}}/api/products/999999
X-Correlation-ID: e7319a6e-899d-413d-9ddb-d1848717bb98
Accept: application/json

###

POST http://localhost:5138/api/products
X-Correlation-ID: e7319a6e-899d-413d-9ddb-d1848717bb98
accept: text/plain
Content-Type: application/json

{
  "name": "Lemon",
  "stock": 99,
  "price": 0.85
}

###

### 400
PUT http://localhost:5138/api/products/1
X-Correlation-ID: e7319a6e-899d-413d-9ddb-d1848717bb98
accept: */*
Content-Type: application/json

{
  "id": 0,
  "name": "thing",
  "stock": 999,
  "price": 0
}

###

### 400 due to name
PUT http://localhost:5138/api/products/1
X-Correlation-ID: e7319a6e-899d-413d-9ddb-d1848717bb98
accept: */*
Content-Type: application/json

{
  "id": 1,
  "name": "",
  "stock": 999,
  "price": 0
}
###

### 400 stock
PUT http://localhost:5138/api/products/1
X-Correlation-ID: e7319a6e-899d-413d-9ddb-d1848717bb98
accept: */*
Content-Type: application/json

{
  "id": 1,
  "name": "",
  "stock": -1,
  "price": 0
}
###



